name: clean_helper
description: A CLI tool for scaffolding Flutter clean architecture projects.
version: 1.2.0
repository: https://github.com/gktirkha/clean_helper

environment:
  sdk: ^3.11.3

executables:
  clean-helper: clean_helper

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.0
  path: ^1.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  test: ^1.25.6
