name: clean_helpers
description: A CLI tool for scaffolding Flutter clean architecture projects.
version: 1.0.0
repository: https://github.com/my_org/clean_helpers

environment:
  sdk: ^3.11.3

executables:
  clean-helpers: clean_helpers

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
